language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required

services:
  - docker

branches:
  only:
    - master
    - release
    - dev
    - /^.*-wip$/
    - /^(.*\/)?ci-.*$/

before_install:
  - docker run -d --name firebird -p 3050:3050 almeida/firebird
  - docker run -v $(pwd):/dotnet/:rw -e 'CI=True' --name dotnet --link firebird:firebird -d microsoft/dotnet:2.0.0-sdk sh -c 'while true; do sleep 0.1; done'

script:
  - docker exec -it dotnet sh -c 'cd /dotnet/EntityFrameworkCore.FirebirdSql && dotnet restore' 

notifications:
    email:
        recipients:
            - jean.ressouche@souchprod.com
            - ralms@ralms.net
        on_success: always
        on_failure: always
