version: '0.0.0.{build}'
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
configuration:
  - Release
environment:
  matrix:  
  - name: FB 3.2
    fb_download: https://www.dropbox.com/s/4o6nvoahmlegv64/binarios.7z?dl=1
shallow_clone: true
test: off
before_build:
  - ps: $baseDir = Resolve-Path .
build_script:
  - ps: $env:build_nuget = 'C:\Program Files\AppVeyor\BuildAgent\Tools\nuget.exe'
after_build:
  - ps: mkdir "$baseDir\out" | Out-Null
  - ps: gci "$baseDir\out" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
before_test:
  - ps: $testsBaseDir = "$baseDir\EFCore.FirebirdSql.FunctionalTests"
  - ps: mkdir C:\firebirdefcore | Out-Null
  - ps: cd C:\firebirdefcore
  - ps: Start-FileDownload "$env:fb_download" | Out-Null
  - ps: 7z x ($env:fb_download -replace '.+/([^/]+)\?dl=1','$1')
  - ps: .\firebird.exe -a
test_script:
  - ps: cd $testsBaseDir
  - ps: dotnet restore
  - ps: dotnet test EFCore.FirebirdSql.FunctionalTests.csproj
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Email
  to:
  - ralms@ralms.net
  subject: EntityframeworkCore.FirebirdSql
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
